[workspace]
name = "unitree_ros2_env"
platforms = ["linux-64"]
channels = ["conda-forge", "nvidia"]

[feature.common.dependencies]
pip = "*"
python = "*"
numpy = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
colcon-common-extensions = "*"
catkin_tools = "*"
rosdep = "*"
tqdm = "*"


[feature.humble]
channels = ["https://repo.prefix.dev/robostack-staging"]

[feature.humble.dependencies]
ros-humble-desktop = "*"
ros-humble-rmw-cyclonedds-cpp = "*"
ros-humble-rosidl-generator-dds-idl = "*"
ros-humble-plotjuggler-ros = "*"

[feature.lyrical]
channels = ["https://repo.prefix.dev/robostack-lyrical"]

[feature.lyrical.dependencies]
ros-lyrical-desktop = "*"
ros-lyrical-rmw-cyclonedds-cpp = "*"
ros-lyrical-plotjuggler-ros = "*"

[environments]
humble = ["common", "humble"]
lyrical = ["common", "lyrical"]
